sudo: required
dist: xenial

before_script:
  - git clone --depth 1 -b "v0.5.1" --single-branch https://github.com/k8s-school/kind-travis-ci.git
  - ./kind-travis-ci/kind/k8s-create.sh
  - export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
#  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - ./build.sh
  - ./deploy.sh
  - ./wait-app-ready.sh 
  - kubectl get all,endpoints,cm,pvc,pv -o wide
  - ./run-integration-tests.sh

# after_success:
  # - echo "Push ci-example image to Docker Hub"
  # - docker push k8s-school/ci-example:latest
